### ISSUE TITLE
멤버용 - 회원가입 직후 나오는 소속 팀 선택 화면 구현 

### ISSUE THREAD

**Issue by jsh-me** [YAPP-admin/attendance-android#10]
카카오 로그인 직후 자신의 소속팀을 선택하는 화면을 구현합니다.

|소속 선택 화면|
|:---:|
|<img src="https://user-images.githubusercontent.com/39688690/154850380-d46017cb-2066-4d02-9361-337308c63002.png" width="50%">|

**Comment by junieberry** [comment]
소속 팀은 firebase에서 가지고 오면 될까요?

**Comment by jsh-me** [comment]
넹!
