### ISSUE TITLE
출석이 필요하지 않은 세션이 일괄 결석 처리가 되어 있는 문제

### ISSUE THREAD

**Issue by jihee-dev** [YAPP-admin/attendance-android#127]
## ISSUE

**작업 내용**
- 출석이 필요하지 않은 휴얍, 팀세션의 경우 모든 멤버의 출석 정보가 출석으로 적용되도록 수정

**스크린샷**

| Screen Name | Screen Name |
| ----------- | ----------- |
|             |             |

**체크리스트**

- [ ] 출석이 필요하지 않은 세션의 출석 정보를 출석으로 적용

**Comment by junieberry** [comment]
이 부분 #124 에서 해결해서 닫겠습니다!!
