### ISSUE TITLE
StatusBar 투명처리

### ISSUE THREAD

**Issue by toastmeister1** [YAPP-admin/attendance-android#143]
## ISSUE or BUG

**작업 내용**
모든 화면의 StatusBar를 투명하게 처리 합니다

**스크린샷**

| Screen Name | Screen Name |
| ----------- | ----------- |
|      ![image](https://user-images.githubusercontent.com/53253298/169559021-980a1205-43d9-4967-be99-34d9f6bb11e2.png)|          ![image](https://user-images.githubusercontent.com/53253298/169559150-c847cefe-9c86-4ae6-9f66-9d2ccf852c33.png) |

**Comment by jsh-me** [comment]
@toastmeister1 요거 제가 가져갈게유~
