### ISSUE TITLE
[Dev] Debug앱 과 Release앱을 구분했으면 좋겠어요

### ISSUE THREAD

**Issue by toastmeister1** [YAPP-admin/attendance-android#211]
## ISSUE or BUG

**작업 내용**
- 개발할때 어떤 앱이 개발용인지 인식하기 어려운 문제

**스크린샷**

| Screen Name | Screen Name |
| ----------- | ----------- |
|             |             |

**체크리스트**

- [ ] Todo
- [ ] Todo
- [ ] Todo

**Comment by TaeseongYun** [comment]
example

documents -> firestore document 네이밍 구분짓기 위한 config value


```gradle

android {
    debug {
          buildConfigField String documents "yapp-22th-debug"
          applicationIdSuffix ".debug"
    }
    
    release {
          buildConfigField String documents "yapp-22th"
    }
}
```

**Comment by TaeseongYun** [comment]
https://firebase.google.com/docs/app-distribution/android/distribute-fastlane?hl=ko

fastlane 선택
이유 ? -> firebase app distribution 으로 앱 배포가 이뤄질 예정인데 공식문서의 한종류이기 때문에 채택.

**Comment by TaeseongYun** [comment]
참고 자료

fastlane 설치 -> https://docs.fastlane.tools/getting-started/android/setup/
ruby permission 이슈 -> https://jojoldu.tistory.com/288

https://dongsik93.github.io/til/2022/03/03/til-android-fastlane-app-distribution/

play 관리자 권한이 필요하다..

fastlane -- env 파일을 사용하여 app id 처리

**Comment by jihee-dev** [comment]
@TaeseongYun 이 코멘트를 지금 봤네요! play 관리자 권한 지금 바로 추가하러 갑니다~!

**Comment by TaeseongYun** [comment]
> @TaeseongYun ~이 코멘트를 지금 봤네요! play 관리자 권한 지금 바로 추가하러 갑니다!~ 지금 보니까 이미 관리자 권한이 부여된 것으로 보이는데 혹시 게시자(소유자?) 권한이 필요한 걸까요?

네 게시자 권한이 필요합니다 ~
그 이유는 google play api 엑세스가 필요한데 게시가자 아니어서 안된다 하더라구요

게시자와 관리자는 권한이 조금 다른가보군요 🤔
