### ISSUE TITLE
[Bug] Scaffold InnerPadding 설정에 따라 변동된 UI 수정

### ISSUE THREAD

**Issue by hoyahozz** [YAPP-admin/attendance-android#224]
## ISSUE or BUG

**작업 내용**

현재 파악한 화면은 아래의 두 화면이지만, 점검이 필요할 것 같습니다!

**스크린샷**

| 관리자 - 전체 세션(Management) | 회원가입 - 직군 선택(Position) |
| ----------- | ----------- |
|  ![Screenshot_1681838005 중간](https://user-images.githubusercontent.com/85336456/232853645-42b92bef-7172-470d-ae7b-d8fcd732ecb3.jpeg)           |        ![Screenshot_1681837935 중간](https://user-images.githubusercontent.com/85336456/232853680-cb78fb4b-ed74-4ae1-a591-f1f5afe4706c.jpeg)     |

**체크리스트**

- [ ] Todo
- [ ] Todo
- [ ] Todo

**Comment by toastmeister1** [comment]
https://github.com/YAPP-admin/attendance-android/pull/218/commits/2e80a6650def9476241157df4f85bb5dab37932d
해당 이슈는 위의 PR에서 제가 깨지는거 빠르게 해결하려고 무지성 innerPadding을 줘서 발생한 문제입니다;;
이 이슈는 제가 가져갈게요
