### ISSUE TITLE
Compose 와 호환되는 QR Library 조사

### ISSUE THREAD

**Issue by jsh-me** [YAPP-admin/attendance-android#6]
어떤 기능을 제공하는지 기록할 것

**Comment by jihee-dev** [comment]
기존에 찾아봤던 Zxing 라이브러리 그대로 사용 가능할 것 같습니다
일단 남겨놓고 정리해 볼게요!

* 레퍼런스
https://youtu.be/asl1mFtkMkc
https://youtu.be/A8r_sY7zJgE

**Comment by jsh-me** [comment]
https://codesandbox.io/s/yp1pmpjo4z
